dataset:
    test_size: 0.25
    random_state: 10
    max_seq_len: 100

train:
    epochs: 16
    batch_size: 32

embedding:
    num_nodes: 100
    input_len: 100

dropout:
    val: 0.3

lstm:
    num_units: 128
    dropout: 0.2

